import type { FlatToken, OutputFormat } from "./types";

export function generate(tokens: FlatToken[], format: OutputFormat): string {
  switch (format) {
    case "css":
      return generateCSS(tokens);
    case "scss":
      return generateSCSS(tokens);
    case "tailwind":
      return generateTailwind(tokens);
    case "ts":
      return generateTypeScript(tokens);
    case "json":
      return generateJSON(tokens);
    default:
      throw new Error(`Unknown format: ${format}`);
  }
}

function generateCSS(tokens: FlatToken[]): string {
  const lines = [
    "/* Auto-generated by design-tokens-pipeline — DO NOT EDIT */",
    "",
    ":root {",
  ];

  // Group by type for readability
  const grouped = groupByType(tokens);
  for (const [type, typeTokens] of Object.entries(grouped)) {
    lines.push(`  /* ${type || "other"} */`);
    for (const token of typeTokens) {
      lines.push(`  ${token.cssVar}: ${token.value};`);
    }
    lines.push("");
  }

  lines.push("}");
  return lines.join("\n");
}

function generateSCSS(tokens: FlatToken[]): string {
  const lines = [
    "// Auto-generated by design-tokens-pipeline — DO NOT EDIT",
    "",
  ];

  for (const token of tokens) {
    const scssVar = `$${token.name}`;
    lines.push(`${scssVar}: ${token.value};`);
  }

  return lines.join("\n");
}

function generateTailwind(tokens: FlatToken[]): string {
  const theme: Record<string, Record<string, string>> = {};

  for (const token of tokens) {
    const category = token.path[0];
    const key = token.path.slice(1).join("-") || "DEFAULT";

    if (!theme[category]) theme[category] = {};
    theme[category][key] = `var(${token.cssVar})`;
  }

  const lines = [
    "// Auto-generated by design-tokens-pipeline — DO NOT EDIT",
    "// Use with: theme: { extend: { ...tokens } }",
    "",
    `export const tokens = ${JSON.stringify(theme, null, 2)} as const;`,
  ];

  return lines.join("\n");
}

function generateTypeScript(tokens: FlatToken[]): string {
  const lines = [
    "// Auto-generated by design-tokens-pipeline — DO NOT EDIT",
    "",
    "export const tokens = {",
  ];

  for (const token of tokens) {
    const constName = token.path
      .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
      .join("");
    lines.push(
      `  /** ${token.type ?? "token"}: ${token.value} */`
    );
    lines.push(`  ${constName}: "${token.value}",`);
  }

  lines.push("} as const;");
  lines.push("");
  lines.push("export type TokenKey = keyof typeof tokens;");
  return lines.join("\n");
}

function generateJSON(tokens: FlatToken[]): string {
  const obj: Record<string, { value: string; cssVar: string; type?: string }> = {};
  for (const token of tokens) {
    obj[token.name] = {
      value: token.value,
      cssVar: token.cssVar,
      type: token.type,
    };
  }
  return JSON.stringify(obj, null, 2);
}

function groupByType(tokens: FlatToken[]): Record<string, FlatToken[]> {
  const groups: Record<string, FlatToken[]> = {};
  for (const token of tokens) {
    const type = token.type ?? "other";
    if (!groups[type]) groups[type] = [];
    groups[type].push(token);
  }
  return groups;
}
